version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 465406024893.dkr.ecr.us-east-2.amazonaws.com
      - IMAGE_NAME="sample-node-app"
      - REPOSITORY_URI=465406024893.dkr.ecr.us-east-2.amazonaws.com/sample-node-app
      - IMAGE_TAG=prod_$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $IMAGE_TAG
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Image_tag $IMAGE_TAG
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo $(docker images)
      #- docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push 465406024893.dkr.ecr.us-east-2.amazonaws.com/sample-node-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"helloworld","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json